/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteRouteImport } from './routes/$project/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/$project/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ProjectSprintsIndexRouteImport } from './routes/$project/sprints/index'
import { Route as ProjectSettingsIndexRouteImport } from './routes/$project/settings/index'
import { Route as ProjectMyIssuesIndexRouteImport } from './routes/$project/my-issues/index'
import { Route as ProjectMembersIndexRouteImport } from './routes/$project/members/index'
import { Route as ProjectIssuesIndexRouteImport } from './routes/$project/issues/index'
import { Route as ProjectInboxIndexRouteImport } from './routes/$project/inbox/index'
import { Route as ProjectEpicsIndexRouteImport } from './routes/$project/epics/index'
import { Route as ProjectDraftsIndexRouteImport } from './routes/$project/drafts/index'
import { Route as ProjectArchivedIndexRouteImport } from './routes/$project/archived/index'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSprintsIndexRoute = ProjectSprintsIndexRouteImport.update({
  id: '/sprints/',
  path: '/sprints/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectSettingsIndexRoute = ProjectSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectMyIssuesIndexRoute = ProjectMyIssuesIndexRouteImport.update({
  id: '/my-issues/',
  path: '/my-issues/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectMembersIndexRoute = ProjectMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectIssuesIndexRoute = ProjectIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectInboxIndexRoute = ProjectInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectEpicsIndexRoute = ProjectEpicsIndexRouteImport.update({
  id: '/epics/',
  path: '/epics/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectDraftsIndexRoute = ProjectDraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectArchivedIndexRoute = ProjectArchivedIndexRouteImport.update({
  id: '/archived/',
  path: '/archived/',
  getParentRoute: () => ProjectRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$project': typeof ProjectRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/$project/': typeof ProjectIndexRoute
  '/$project/archived': typeof ProjectArchivedIndexRoute
  '/$project/drafts': typeof ProjectDraftsIndexRoute
  '/$project/epics': typeof ProjectEpicsIndexRoute
  '/$project/inbox': typeof ProjectInboxIndexRoute
  '/$project/issues': typeof ProjectIssuesIndexRoute
  '/$project/members': typeof ProjectMembersIndexRoute
  '/$project/my-issues': typeof ProjectMyIssuesIndexRoute
  '/$project/settings': typeof ProjectSettingsIndexRoute
  '/$project/sprints': typeof ProjectSprintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/$project': typeof ProjectIndexRoute
  '/$project/archived': typeof ProjectArchivedIndexRoute
  '/$project/drafts': typeof ProjectDraftsIndexRoute
  '/$project/epics': typeof ProjectEpicsIndexRoute
  '/$project/inbox': typeof ProjectInboxIndexRoute
  '/$project/issues': typeof ProjectIssuesIndexRoute
  '/$project/members': typeof ProjectMembersIndexRoute
  '/$project/my-issues': typeof ProjectMyIssuesIndexRoute
  '/$project/settings': typeof ProjectSettingsIndexRoute
  '/$project/sprints': typeof ProjectSprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$project': typeof ProjectRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/$project/': typeof ProjectIndexRoute
  '/$project/archived/': typeof ProjectArchivedIndexRoute
  '/$project/drafts/': typeof ProjectDraftsIndexRoute
  '/$project/epics/': typeof ProjectEpicsIndexRoute
  '/$project/inbox/': typeof ProjectInboxIndexRoute
  '/$project/issues/': typeof ProjectIssuesIndexRoute
  '/$project/members/': typeof ProjectMembersIndexRoute
  '/$project/my-issues/': typeof ProjectMyIssuesIndexRoute
  '/$project/settings/': typeof ProjectSettingsIndexRoute
  '/$project/sprints/': typeof ProjectSprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$project'
    | '/auth/sign-in'
    | '/$project/'
    | '/$project/archived'
    | '/$project/drafts'
    | '/$project/epics'
    | '/$project/inbox'
    | '/$project/issues'
    | '/$project/members'
    | '/$project/my-issues'
    | '/$project/settings'
    | '/$project/sprints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/$project'
    | '/$project/archived'
    | '/$project/drafts'
    | '/$project/epics'
    | '/$project/inbox'
    | '/$project/issues'
    | '/$project/members'
    | '/$project/my-issues'
    | '/$project/settings'
    | '/$project/sprints'
  id:
    | '__root__'
    | '/'
    | '/$project'
    | '/auth/sign-in'
    | '/$project/'
    | '/$project/archived/'
    | '/$project/drafts/'
    | '/$project/epics/'
    | '/$project/inbox/'
    | '/$project/issues/'
    | '/$project/members/'
    | '/$project/my-issues/'
    | '/$project/settings/'
    | '/$project/sprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$project': {
      id: '/$project'
      path: '/$project'
      fullPath: '/$project'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project/': {
      id: '/$project/'
      path: '/'
      fullPath: '/$project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project/sprints/': {
      id: '/$project/sprints/'
      path: '/sprints'
      fullPath: '/$project/sprints'
      preLoaderRoute: typeof ProjectSprintsIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/settings/': {
      id: '/$project/settings/'
      path: '/settings'
      fullPath: '/$project/settings'
      preLoaderRoute: typeof ProjectSettingsIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/my-issues/': {
      id: '/$project/my-issues/'
      path: '/my-issues'
      fullPath: '/$project/my-issues'
      preLoaderRoute: typeof ProjectMyIssuesIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/members/': {
      id: '/$project/members/'
      path: '/members'
      fullPath: '/$project/members'
      preLoaderRoute: typeof ProjectMembersIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/issues/': {
      id: '/$project/issues/'
      path: '/issues'
      fullPath: '/$project/issues'
      preLoaderRoute: typeof ProjectIssuesIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/inbox/': {
      id: '/$project/inbox/'
      path: '/inbox'
      fullPath: '/$project/inbox'
      preLoaderRoute: typeof ProjectInboxIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/epics/': {
      id: '/$project/epics/'
      path: '/epics'
      fullPath: '/$project/epics'
      preLoaderRoute: typeof ProjectEpicsIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/drafts/': {
      id: '/$project/drafts/'
      path: '/drafts'
      fullPath: '/$project/drafts'
      preLoaderRoute: typeof ProjectDraftsIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/$project/archived/': {
      id: '/$project/archived/'
      path: '/archived'
      fullPath: '/$project/archived'
      preLoaderRoute: typeof ProjectArchivedIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
  }
}

interface ProjectRouteRouteChildren {
  ProjectIndexRoute: typeof ProjectIndexRoute
  ProjectArchivedIndexRoute: typeof ProjectArchivedIndexRoute
  ProjectDraftsIndexRoute: typeof ProjectDraftsIndexRoute
  ProjectEpicsIndexRoute: typeof ProjectEpicsIndexRoute
  ProjectInboxIndexRoute: typeof ProjectInboxIndexRoute
  ProjectIssuesIndexRoute: typeof ProjectIssuesIndexRoute
  ProjectMembersIndexRoute: typeof ProjectMembersIndexRoute
  ProjectMyIssuesIndexRoute: typeof ProjectMyIssuesIndexRoute
  ProjectSettingsIndexRoute: typeof ProjectSettingsIndexRoute
  ProjectSprintsIndexRoute: typeof ProjectSprintsIndexRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectArchivedIndexRoute: ProjectArchivedIndexRoute,
  ProjectDraftsIndexRoute: ProjectDraftsIndexRoute,
  ProjectEpicsIndexRoute: ProjectEpicsIndexRoute,
  ProjectInboxIndexRoute: ProjectInboxIndexRoute,
  ProjectIssuesIndexRoute: ProjectIssuesIndexRoute,
  ProjectMembersIndexRoute: ProjectMembersIndexRoute,
  ProjectMyIssuesIndexRoute: ProjectMyIssuesIndexRoute,
  ProjectSettingsIndexRoute: ProjectSettingsIndexRoute,
  ProjectSprintsIndexRoute: ProjectSprintsIndexRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
